### ISSUE TITLE
Overflow bug in Safari

### ISSUE THREAD

**Issue by brandonstephens** [doeanderson/trello-mod#1]
![screen shot 2016-06-09 at 2 11 01 pm](https://cloud.githubusercontent.com/assets/838662/15940908/0dd26a94-2e4c-11e6-9eed-3925745123fa.png)

**Comment by patrickhill** [comment]
You talking about the edit/pencil icon button?

**Comment by brandonstephens** [comment]
No, there is a scrollbar behind it. The hover state is hidden and causing scrollbar I think.

**Comment by patrickhill** [comment]
Should be good now
